### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by August0** [August0/hello-world#1]
so that the humans "get" me

**Comment by FabioZTessitore** [comment]
che significa?

**Comment by August0** [comment]
Quando ho fatto l'account c'era un esempio che ti faceva capire un po' di
cose...e questo era un esempio per capire che cosa sono le issue

2015-12-08 14:32 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Le issue sono le cose da fare nel progetto. Per il momento le gestisco io. Qui troverai cosa devi fare
